import {humanMemoryScene,humanMemoryMarkup} from './reading-memory.mjs';
/* Teaching constructions are deliberately separate from claims about trained
 * models, measured neural activity, and behavioral effects of institutions. */
(() => {
'use strict';
const $=id=>document.getElementById(id), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n).toFixed(3), v=x=>'['+x.map(n=>Number(n).toFixed(2)).join(', ')+']';
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let tab='intro',machinePanel='games',caseKey='cat',mode='train',theta=.15,updates=0;
let moment=0,humanTimer=null,humanFrame=0,humanStarted=0,humanElapsed=0,humanCompleted=false,brain=null,brainPromise=null,social='capture',prediction='',revealed=false;
let comparison=null,comparisonPromise=null,brainOpacity=.5;
// ---------- chapters ----------
const CHAPTERS=[
 {id:'intro',part:'',n:0,title:'Start here',short:'Start here'},
 {id:'paper',part:'I',n:1,title:'The paper and the idea',short:'The paper'},
 {id:'queries',part:'I',n:2,title:'Query, key, value',short:'Query, key, value'},
 {id:'practice',part:'I',n:3,title:'Build it: six puzzles',short:'Six puzzles'},
 {id:'training',part:'I',n:4,title:'Training and inference',short:'Training'},
 {id:'numbers',part:'I',n:5,title:'The numbers, under a microscope',short:'The numbers',optional:true},
 {id:'human',part:'II',n:6,title:'Three attention systems',short:'Three systems'},
 {id:'compare',part:'III',n:7,title:'Read and predict together',short:'Read together'},
 {id:'social',part:'IV',n:8,title:'Run the feed, then break it',short:'Run the feed'},
 {id:'society',part:'IV',n:9,title:'More ways to score reading',short:'Scoreboards',optional:true},
 {id:'synthesis',part:'',n:10,title:'What has been understood?',short:'Synthesis'}];
const PARTS={I:'Part I · The machine',II:'Part II · The reader',III:'Part III · Compared',IV:'Part IV · The economy'};
const names=CHAPTERS.map(c=>c.id),LEGACY={framing:'intro',machine:'paper',games:'practice',query:'queries',vectors:'numbers'};
let visited=new Set();try{visited=new Set(JSON.parse(localStorage.getItem('spotlight-visited')||'[]').filter(id=>names.includes(id)));}catch{}
const caseIndices={cat:8,glass:9,machines:5};
function current(){const data=window.ATTENTION_DEMOS[caseKey],index=caseIndices[caseKey];return{...data,key:caseKey,index,prefix:data.toks.slice(0,index+1),next:data.steps[index].next,target:data.toks[index+1]};}
const prefixHTML=()=>current().prefix.map(esc).join(' ')+' <span class="blank">…</span>';
function pauseFrames(){for(const id of ['intro-frame','games-frame','vectors-frame'])$(id)?.contentWindow?.postMessage({type:'attention-pause'},location.origin);}
function chapter(id){return CHAPTERS.find(c=>c.id===id);}
function renderRail(){const c=chapter(tab),i=CHAPTERS.indexOf(c);let html='<button type="button" class="rail-close" id="rail-close">Close contents ✕</button><ol>',part=null;
 for(const ch of CHAPTERS){if(ch.part!==part){part=ch.part;if(part)html+='<li class="rail-part">'+PARTS[part]+'</li>';}
  html+='<li><button type="button" id="tab-'+ch.id+'" data-go="'+ch.id+'" class="'+(visited.has(ch.id)?'visited':'')+(ch.optional?' optional':'')+'" aria-current="'+(ch.id===tab?'page':'false')+'" tabindex="'+(ch.id===tab?0:-1)+'"><span class="rail-n">'+String(ch.n).padStart(2,'0')+'</span><strong>'+esc(ch.short)+'</strong><span class="rail-check" aria-hidden="true">✓</span></button></li>';}
 html+='</ol><p class="rail-foot">'+visited.size+' of '+CHAPTERS.length+' chapters visited. <button type="button" id="rail-reset">Reset</button></p>';$('chapter-rail').innerHTML=html;
 $('chapter-title').innerHTML='<small>'+(c.n?'Chapter '+c.n+' of '+(CHAPTERS.length-1):'Start')+(c.part?' · '+PARTS[c.part]:'')+'</small><strong>'+esc(c.title)+'</strong>';$('chapter-prev').disabled=i===0;$('chapter-next').disabled=i===CHAPTERS.length-1;}
function renderChapterNavs(){CHAPTERS.forEach((c,i)=>{const el=document.querySelector('#'+c.id+' [data-nav]');if(!el)return;const prev=CHAPTERS[i-1],next=CHAPTERS[i+1];
 el.innerHTML=(prev?'<button type="button" data-go="'+prev.id+'">← '+(prev.n?'Chapter '+prev.n:'Start')+' · '+esc(prev.short)+'</button>':'')+(next?'<button type="button" class="primary" data-go="'+next.id+'">Next · '+(next.n?'Chapter '+next.n+' · ':'')+esc(next.title)+' →</button>':'');});}
function go(id,focus=false){id=LEGACY[id]||id;if(!names.includes(id))id='intro';stopHuman();comparison?.pause();pauseFrames();tab=id;visited.add(id);try{localStorage.setItem('spotlight-visited',JSON.stringify([...visited]));}catch{}
 $$('.chapter').forEach(p=>p.hidden=p.id!==id);$('shared-reading').hidden=id==='intro'||id==='synthesis';history.replaceState(null,'','#'+id);setContents(false);renderRail();
 if(id==='numbers'&&!$('vectors-frame').getAttribute('src'))$('vectors-frame').src=$('vectors-frame').dataset.src;
 if(brain)brain.setVisible(id==='human');if(id==='human')loadBrain();comparison?.setVisible(id==='compare');if(id==='compare')loadComparison();
 if(focus){const b=$('tab-'+id);if(b&&b.offsetParent)b.focus({preventScroll:true});else $('lab').focus({preventScroll:true});}}
function setContents(open){$('shell-grid').dataset.contents=open?'open':'closed';$('chapter-contents').setAttribute('aria-expanded',String(open));if(open){const b=$('tab-'+tab);if(b)b.focus({preventScroll:true});}}
function jump(id){go(id);$('lab').scrollIntoView({behavior:'instant'});$('lab').focus({preventScroll:true});}
document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b){if(b.closest('#chapter-rail'))go(b.dataset.go,true),$('lab').scrollIntoView({behavior:'instant'});else jump(b.dataset.go);return;}
 if(e.target.closest('#chapter-contents')){setContents($('shell-grid').dataset.contents!=='open');return;}if(e.target.closest('#rail-close')){setContents(false);$('chapter-contents').focus();return;}
 if(e.target.closest('#rail-reset')){visited=new Set([tab]);try{localStorage.setItem('spotlight-visited',JSON.stringify([...visited]));}catch{}renderRail();return;}
 if(e.target.closest('#chapter-prev')){const i=names.indexOf(tab);if(i>0)jump(names[i-1]);return;}if(e.target.closest('#chapter-next')){const i=names.indexOf(tab);if(i<names.length-1)jump(names[i+1]);}});
$('chapter-rail').addEventListener('keydown',e=>{if(!e.target.closest('[data-go]'))return;let i=names.indexOf(tab);if(e.key==='ArrowRight'||e.key==='ArrowDown')i=(i+1)%names.length;else if(e.key==='ArrowLeft'||e.key==='ArrowUp')i=(i+names.length-1)%names.length;else if(e.key==='Home')i=0;else if(e.key==='End')i=names.length-1;else return;e.preventDefault();go(names[i],true);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('shell-grid').dataset.contents==='open')setContents(false);});
addEventListener('hashchange',()=>{const name=location.hash.slice(1),id=LEGACY[name]||name;if(!names.includes(id))return;if(id!==tab)go(id);else if(location.hash!=='#'+id)history.replaceState(null,'','#'+id);});
addEventListener('message',e=>{if(e.origin!==location.origin||e.data?.type!=='attention-height')return;const f={games:'games-frame',intro:'intro-frame',vectors:'vectors-frame'}[e.data.id];const frame=f?$(f):null;if(frame&&e.source===frame.contentWindow&&Number.isFinite(e.data.height))frame.style.height=Math.max(300,Math.min(18000,e.data.height))+'px';});
window.spotlightGo=(id,focus)=>{go(id,focus);$('lab').scrollIntoView({behavior:'instant'});};
$('demo-shared').addEventListener('click',()=>{$('intro-frame').contentWindow.postMessage({type:'attention-context',key:caseKey,index:current().index},location.origin);});
$('reading-case').addEventListener('change',e=>{caseKey=e.target.value;prediction='';revealed=false;$('human-prediction').value='';$('human-reason').value='';$('prediction-feedback').textContent='';$('social-feedback').textContent='';stopHuman();humanElapsed=0;humanCompleted=false;resetTraining();renderShared();comparison?.contextChanged();});
function renderShared(){$('shared-prefix').innerHTML=prefixHTML();$('compare-prefix').innerHTML=prefixHTML();renderHuman();renderComparison();renderSocial();}
// The query calculation uses row vectors, matching Vaswani et al.
const embeddings={it:[.2,.8],cat:[.9,.1],was:[.4,.5]};
function renderQuery(){const word=$('q-token').value,pos=+$('q-position').value,embedding=embeddings[word],scaled=embedding.map(x=>Math.sqrt(2)*x),position=[Math.sin(pos),Math.cos(pos)],x=scaled.map((a,i)=>a+position[i]),w=+$('q-weight').value;
 const WQ=[[.5,-.3],[w,.4]],WK=[[.7,.1],[-.2,.9]],WV=[[.3,.8],[.6,-.1]];
 const mul=W=>[0,1].map(j=>x.reduce((sum,xi,i)=>sum+xi*W[i][j],0));
 $('q-origin').innerHTML=`<div>“${esc(word)}”<span>lookup learned embedding<br>${v(embedding)}</span></div><b>→</b><div>√2 × embedding<span>${v(scaled)}</span></div><b>+</b><div>Position ${pos}<span>[sin(${pos}), cos(${pos})]<br>${v(position)}</span></div><b>=</b><div>Input x<span>${v(x)}</span></div>`;
 $('q-math').innerHTML=`x = ${v(x)}<br>W<sub>Q</sub> = [ ${v(WQ[0])}<br>　　　 ${v(WQ[1])} ]<br><br>q₁ = ${fmt(x[0])} × 0.5 + ${fmt(x[1])} × ${w.toFixed(1)} = ${fmt(mul(WQ)[0])}<br>q₂ = ${fmt(x[0])} × −0.3 + ${fmt(x[1])} × 0.4 = ${fmt(mul(WQ)[1])}<br><b>q = xW<sub>Q</sub> = ${v(mul(WQ))}</b>`;
 $('q-weight-label').textContent=w.toFixed(1);$('qkv').innerHTML=[['Q',WQ],['K',WK],['V',WV]].map(([name,W])=>`<div class="qkv-row"><strong>${name}</strong><span>x × W<sub>${name}</sub> = ${v(mul(W))}</span></div>`).join('');
}
for(const id of ['q-token','q-position'])$(id).addEventListener('change',renderQuery);$('q-weight').addEventListener('input',renderQuery);$('q-reset').addEventListener('click',()=>{$('q-weight').value=.8;renderQuery();});
// Actual one-example differentiation: q=theta; keys/values=(-1,+1),
// z=tanh(q); vocabulary logits=(2z,-2z); target is candidate zero.
function trainValues(){const z=Math.tanh(theta),p=1/(1+Math.exp(-4*z)),loss=-Math.log(p),gradient=4*(p-1)*(1-z*z);return{z,p,loss,gradient,a:(1+z)/2};}
function bars(rows){return '<div class="bars">'+rows.map(([word,p],i)=>`<div class="bar ${word==='other tokens'?'rest':''}" data-probability="${p}"><span>${esc(word)}</span><span class="bar-track"><i style="width:${p}%"></i></span><span>${p.toFixed(1)}%</span></div>`).join('')+'</div>';}
function renderTraining(){const c=current(),t=trainValues(),other=c.next.find(([w])=>w!==c.target)[0];$('train-title').textContent=c.prefix.join(' ')+' …';$('mode-train').setAttribute('aria-pressed',mode==='train');$('mode-infer').setAttribute('aria-pressed',mode==='infer');$('learn-once').hidden=mode!=='train';$('infer-once').hidden=mode!=='infer';
 $('mode-explanation').innerHTML=mode==='train'?'<p><b>Training: learn from examples with known answers.</b> First predict a word without seeing the answer. Measure the error, work out which weights contributed to it, and adjust them. Repeat over many examples.</p>':'<p><b>Inference: use what training has learned.</b> The answer is unknown. Run the calculation with the stored weights, choose a next token, add it to the text, and repeat. The input and intermediate numbers change; the learned weights stay fixed.</p>';
 const p=c.prefix.slice(-3);$('sequence-grid').innerHTML=`<div>${mode==='train'?'Shifted target input (known during training)':'Target prefix available so far'}</div><div class="sequence-row">${p.map(esc).map(w=>`<span>${w}</span>`).join('')}<span class="future">${mode==='train'?esc(c.target):'?'}</span></div><div>${mode==='train'?`At this position: predict → compare with target “${esc(c.target)}” → update weights. Other shifted positions can train in parallel under the mask.`:'Predict next → append to prefix → predict again. The shaded next position is unavailable to this query.'}</div>`;
 $('train-bars').innerHTML=bars([[c.target,100*t.p],[other,100*(1-t.p)]]);$('theta').textContent=fmt(theta);$('loss').textContent=mode==='train'?fmt(t.loss):'—';$('updates').textContent=updates;
 $('train-math').innerHTML=`The prefix is represented by the authored scalar x = 1. Query q = xθ = ${fmt(theta)}. Two source keys and values are −1 and +1 (dₖ = 1). Attention on the +1 value is ${fmt(t.a)}. The mixture z = tanh(q) = ${fmt(t.z)}. Vocabulary logits are [2z, −2z]. Softmax gives P(“${esc(c.target)}”) = ${fmt(t.p)}.<br><br>${mode==='train'?`Target loss L = −log P = ${fmt(t.loss)}. The chain rule gives ∂L/∂θ = 4(P−1)(1−z²) = ${fmt(t.gradient)}. “Learn once” applies θ ← θ − 0.15 × ∂L/∂θ.`:'No loss or gradient is needed to generate a token. This two-candidate vocabulary and authored x do not capture the real sentence’s meaning.'}`;
}
function resetTraining(){theta=.15;updates=0;$('train-feedback').textContent='';renderTraining();}
$('learn-once').addEventListener('click',()=>{const before=trainValues();theta-=.15*before.gradient;updates++;renderTraining();$('train-feedback').textContent=`Update ${updates}: target loss ${fmt(before.loss)} → ${fmt(trainValues().loss)}. θ changed by ${fmt(-.15*before.gradient)}.`;});
$('infer-once').addEventListener('click',()=>{const c=current(),t=trainValues(),other=c.next.find(([w])=>w!==c.target)[0];$('train-feedback').textContent=`Greedy choice: “${t.p>=.5?c.target:other}”. Append it to the prefix. θ stays ${fmt(theta)}; updates stay ${updates}. A full decoder would now run again on the extended context.`;});
for(const [id,m] of [['mode-train','train'],['mode-infer','infer']])$(id).addEventListener('click',()=>{mode=m;$('train-feedback').textContent='';renderTraining();});$('train-reset').addEventListener('click',resetTraining);
// Coordinates are approximate author placements in native surface RAS millimeters.
// They are not stereotactic measurements from Petersen & Posner.
const moments=[
 {label:'Get ready',family:'Alerting',color:'#e8e8e8',description:'You see “get ready” before the sentence appears. Alerting helps you become ready to respond. A brief cue raises readiness for a moment; sustained alertness keeps you responsive over time.',takeaway:'The lights mark a small brainstem region (the locus coeruleus), the thalamus, and areas toward the front and back of the right cortex. Together they illustrate the alerting system. Being ready is different from deciding which word to read.',event:'Get ready: you will be asked to predict the next word.',source:'Petersen & Posner: Alerting, manuscript PDF pp. 2, 4–5; Fig. 1. Reading application, not a reported brain scan.',focus:[],nodes:[['Locus coeruleus','Small brainstem region; releases norepinephrine, which changes readiness across the brain.',[4,-35,-25],true],['Thalamus','Deep region associated with alerting; shown as a schematic marker.',[10,-15,8],true],['Right frontal cortex','Approximate cortical region associated with alertness.',[38,32,32]],['Right parietal cortex','Approximate cortical region associated with alertness.',[35,-53,48]]]},
 {label:'Select the text',family:'Orienting · dorsal network',color:'#e8e8e8',description:'You focus on words that help you guess the ending. This is orienting: selecting information for closer attention. The upper, or dorsal, orienting network helps direct that selection toward your goal.',takeaway:'The lights move to frontal eye fields and upper parietal areas on both sides. These regions help direct attention. Language and memory systems also help you understand the words; the highlights are not a recording of your eyes.',event:'Look back over the prefix: which words constrain the continuation?',source:'Petersen & Posner: Orienting, PDF pp. 3, 5–6; Fig. 2a.',focus:'clues',nodes:[['Left frontal eye field','Frontal contribution to goal-directed orienting.',[-30,-8,50]],['Right frontal eye field','Corresponding frontal region.',[30,-8,50]],['Left intraparietal / superior parietal','Parietal contribution to spatial prioritization.',[-26,-58,52]],['Right intraparietal / superior parietal','Corresponding parietal region.',[26,-58,52]]]},
 {label:'Notice a cue',family:'Orienting · ventral network',color:'#e8e8e8',description:'A margin note tells you to check an earlier word. You shift your focus back to it. A mainly right-sided network helps reorient attention when something relevant interrupts what you were doing.',takeaway:'Here the lights mark lower frontal cortex and the junction of the temporal and parietal lobes, mainly on the right. A cue is more likely to matter when it is relevant to your task.',event:'Margin cue: “Check the earlier clue before you guess.”',source:'Petersen & Posner: Orienting, PDF pp. 5–6; Fig. 2a.',focus:'earlier',nodes:[['Right temporoparietal junction','Near temporal and parietal cortex.',[54,-48,20]],['Right ventral frontal cortex','Lower lateral frontal region.',[48,20,8]]]},
 {label:'Keep the purpose',family:'Executive control · cingulo-opercular',color:'#e8e8e8',description:'You keep the instruction “predict the next word” in mind, even after an interruption. Executive control helps maintain this goal while working memory uses the sentence meaning you are holding. Keeping the task active is the role emphasized here for the cingulo-opercular network.',takeaway:'The lights mark regions near the brain’s midline, the insula on each side, frontmost cortex, and the thalamus. They help maintain the task. Lower the opacity to see the buried regions.',event:'The task is still to predict a continuation, even after the cue.',source:'Petersen & Posner: Executive Control, PDF pp. 6–8; Figs. 2b–c, 3. The two-control-network account is the authors’ framework, not an uncontested map.',focus:'last',nodes:[['Dorsal anterior cingulate / medial superior frontal','Midline contribution to control.',[0,22,32],true],['Left anterior insula / frontal operculum','Partly buried cortical control region.',[-34,20,0],true],['Right anterior insula / frontal operculum','Corresponding cortical region.',[34,20,0],true],['Anterior prefrontal cortex','Representative anterior control node.',[25,55,15]],['Thalamus','Schematic deep control node.',[10,-15,8],true]]},
 {label:'Check and revise',family:'Executive control · frontoparietal',color:'#e8e8e8',description:'Your first guess seems wrong, so you reread a clue and consider another word. Executive control also helps you check and adjust what you are doing. The authors associate this flexible control with a frontoparietal network.',takeaway:'The lights now mark side areas of the frontal and parietal cortex on both sides. You are changing your strategy and using the meaning held in working memory. These lights show control support, not a store for the words. This is not the same operation as updating a machine’s weights.',event:'Reread the clue, compare possibilities, then make or revise your guess.',source:'Petersen & Posner: Executive Control, PDF pp. 7–8; Fig. 2b–c. This control network is distinct from dorsal orienting.',focus:'clues',nodes:[['Left dorsolateral prefrontal cortex','Frontal contribution to adaptive control.',[-42,34,28]],['Right dorsolateral prefrontal cortex','Corresponding frontal region.',[42,34,28]],['Left inferior parietal cortex','Parietal contribution to adaptive control.',[-48,-48,42]],['Right inferior parietal cortex','Corresponding parietal region.',[48,-48,42]]]}
];
const emphasis=[[1,.24,.25,.22,.3],[.28,1,.6,.4,.8],[.15,.2,1,.18,.25],[.5,.6,.65,1,.7],[.2,.4,.55,.45,1]];
$('moment-tabs').innerHTML=moments.map((m,i)=>`<button data-moment="${i}" aria-pressed="${i===0}"><span>0${i+1}</span>${m.label}<small>${i===0?'Alerting':i<3?'Orienting':'Executive control'}</small></button>`).join('');
const systems=[{name:'Alerting',letter:'A',purpose:'Get ready to respond.'},{name:'Orienting',letter:'O',purpose:'Choose or shift your focus.'},{name:'Executive control',letter:'E',purpose:'Keep the goal; check your response.'}];
function renderHuman(){const system=systems[moment===0?0:moment<3?1:2];$('brain-system-letter').textContent=system.letter;$('brain-system-title').textContent=system.name;$('brain-system-purpose').textContent=system.purpose;$('regions-title').textContent='Regions highlighted for '+system.name.toLowerCase();$$('[data-system]').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.system===(moment===0?0:moment<3?1:3)));const m=moments[moment],c=current(),clues=caseKey==='cat'?[1,2,7]:caseKey==='glass'?[2,4,8]:[1,4];let focus=m.focus==='clues'?clues:m.focus==='earlier'?[clues[0]]:m.focus==='last'?[c.index]:[];
 $('moment-family').textContent=m.family;$('moment-title').textContent=m.label;$('moment-description').textContent=m.description;$('moment-takeaway').textContent=m.takeaway;$('reading-event').textContent=m.event;$('moment-source').textContent=m.source;$('human-sentence').innerHTML=c.prefix.map((w,i)=>focus.includes(i)?`<mark>${esc(w)}</mark>`:esc(w)).join(' ')+' <span class="blank">…</span>';
 const memory=humanMemoryScene(c.key,moment);$('human-reading-memory').innerHTML=humanMemoryMarkup(memory);$('human-reading-memory').dataset.memoryMode=memory.mode;
 $('region-list').innerHTML=m.nodes.map(([name,note],i)=>`<li><span class="region-number">${i+1}</span><span><b>${name}</b><br><small>${note}</small></span></li>`).join('');$('human-progress').textContent=`Moment ${moment+1} of 5 · ${m.family}`;$('human-prev').disabled=moment===0;$('human-next').disabled=moment===4;$$('button[data-moment]').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.moment===moment));
 $('network-map').innerHTML='<table><thead><tr><th>Network ↓ / Moment →</th>'+moments.map(m=>`<th>${m.label}</th>`).join('')+'</tr></thead><tbody>'+moments.map((m,i)=>`<tr><th>${m.family}</th>${emphasis[i].map((value,j)=>`<td><button data-map-moment="${j}" aria-label="${m.family}, ${moments[j].label}: ${value>.75?'strong':value>.4?'supporting':'background'} illustrative emphasis" aria-pressed="${j===moment}" style="background:color-mix(in srgb,${m.color} ${value*65}%,#161616);color:${value>.6?'#111':'#fff'}">${value>.75?'Strong':value>.4?'Supporting':'Background'}</button></td>`).join('')}</tr>`).join('')+'</tbody></table>';
 $$('[data-map-moment]').forEach(b=>b.addEventListener('click',()=>chooseMoment(+b.dataset.mapMoment)));
 $('brain').setAttribute('aria-label',`${m.family}. Highlighted approximate regions: ${m.nodes.map(n=>n[0]).join(', ')}. Arrow keys rotate; plus and minus zoom; Home resets.`);
 brain?.setMoment(moment,!!humanTimer);renderHumanPlayback();motionNote();
}
$$('[data-system]').forEach(b=>b.addEventListener('click',()=>chooseMoment(+b.dataset.system)));
function chooseMoment(i){stopHuman();moment=i;humanElapsed=0;humanCompleted=false;renderHuman();}
$$('button[data-moment]').forEach(b=>b.addEventListener('click',()=>chooseMoment(+b.dataset.moment)));$('human-prev').addEventListener('click',()=>chooseMoment(Math.max(0,moment-1)));$('human-next').addEventListener('click',()=>chooseMoment(Math.min(4,moment+1)));
// The six-second clock is classroom pacing. It is separate from the renderer's
// illustrative pulses, and still advances when reduced motion is requested.
function renderHumanPlayback(){
 const elapsed=humanTimer?Math.min(6000,humanElapsed+performance.now()-humanStarted):humanElapsed;
 const state=humanTimer?'playing':humanCompleted?'complete':humanElapsed>0?'paused':'ready';
 $('human-playback').dataset.state=state;
 const status=humanTimer?'Playing':humanCompleted?'Sequence complete':humanElapsed>0?'Paused':'Ready to play';
 if($('human-playback-state').textContent!==status)$('human-playback-state').textContent=status;
 $('human-play').textContent=humanTimer?'Pause reading sequence':humanCompleted?'Replay reading sequence':humanElapsed>0?'Resume reading sequence':'Play reading sequence';
 $('human-stage-play').textContent=humanTimer?'Ⅱ Pause':humanCompleted?'↺ Replay':humanElapsed>0?'▶ Resume':'▶ Play';
 for(const id of ['human-play','human-stage-play'])$(id).setAttribute('aria-pressed',!!humanTimer);
 $('human-timeline-fill').style.width=100*elapsed/6000+'%';
 const timeline=$('human-timeline-fill').parentElement;timeline.setAttribute('aria-valuenow',(elapsed/1000).toFixed(1));timeline.setAttribute('aria-valuetext',`${(elapsed/1000).toFixed(1)} of 6 teaching seconds`);
 $('human-clock').textContent=humanCompleted?'5 / 5 moments':`${((6000-elapsed)/1000).toFixed(1)} s`;
 $('human-next-cue').textContent=humanCompleted?'Explore any moment above.':moment===4?'Then: end of sequence':`Next: ${moments[moment+1].label}`;
}
function tickHuman(){humanFrame=0;renderHumanPlayback();if(humanTimer)humanFrame=requestAnimationFrame(tickHuman);}
function stopHuman(){if(humanTimer)humanElapsed=Math.min(6000,humanElapsed+performance.now()-humanStarted);clearTimeout(humanTimer);humanTimer=null;cancelAnimationFrame(humanFrame);humanFrame=0;brain?.setPlaying(false);renderHumanPlayback();}
function scheduleHuman(){humanStarted=performance.now();humanTimer=setTimeout(()=>{humanElapsed=0;if(moment===4){humanElapsed=6000;humanCompleted=true;stopHuman();return;}moment++;scheduleHuman();renderHuman();},6000-humanElapsed);}
function toggleHuman(){if(humanTimer){stopHuman();return;}if(humanCompleted){moment=0;humanElapsed=0;humanCompleted=false;}scheduleHuman();renderHuman();if(!humanFrame)humanFrame=requestAnimationFrame(tickHuman);}
$('human-play').addEventListener('click',toggleHuman);$('human-stage-play').addEventListener('click',toggleHuman);
function motionNote(){$('motion-note').textContent=reduced.matches?'Reduced motion: regions stay steadily lit, with no traveling dots or expanding rings. The progress bar and six-second scene changes remain available.':'During Play, bright regions pulse, red rings expand and white dots move between them. The progress bar counts six teaching seconds per moment. This illustrates coordination, not neural timing or measured signals.';}
reduced.addEventListener('change',()=>{motionNote();brain?.setReducedMotion(reduced.matches);});
async function loadBrain(){if(brain){brain.setVisible(true);return;}if(brainPromise)return;brainPromise=(async()=>{try{$('brain-status').textContent='Loading cortical surface…';const module=await import('./brain.js');brain=await module.createBrain({canvas:$('brain'),labels:$('brain-labels'),moments,emphasis,reduced:reduced.matches,flow:true});brain.setOpacity(brainOpacity);brain.setHemisphere($('hemisphere').value);brain.setMoment(moment,!!humanTimer);brain.setVisible(tab==='human');$('brain-status').textContent='Drag to explore · anatomical surface';$('brain-status').dataset.ready='true';}catch(e){$('brain-status').textContent='3D unavailable · text view active';$('brain-fallback').hidden=false;console.warn('Brain viewer unavailable:',e.message);}})();}
$('rotate-left').addEventListener('click',()=>brain?.rotate(-.3,0));$('rotate-right').addEventListener('click',()=>brain?.rotate(.3,0));$('top-view').addEventListener('click',()=>brain?.top());$('reset-view').addEventListener('click',()=>brain?.reset());$$('[data-brain-opacity]').forEach(input=>input.addEventListener('input',()=>{brainOpacity=+input.value/100;$$('[data-brain-opacity]').forEach(el=>{el.value=brainOpacity*100;$(el.id+'-value').textContent=Math.round(brainOpacity*100)+'%';});brain?.setOpacity(brainOpacity);comparison?.setOpacity(brainOpacity);}));$('hemisphere').addEventListener('change',e=>brain?.setHemisphere(e.target.value));
async function loadComparison(){if(comparison){comparison.setVisible(true);return;}if(comparisonPromise)return;comparisonPromise=(async()=>{try{const module=await import('./comparison.js?v=20260920-memory');comparison=module.createComparison({moments,emphasis,getContext:current,getPrediction:()=>prediction,reduced,opacity:brainOpacity});comparison.setVisible(tab==='compare');}catch(e){$('comparison-progress').textContent='Animation unavailable; the prediction and comparison below remain usable.';console.warn('Comparison unavailable:',e.message);}})();}
// Shared next-token task: the data object also drives the original intro.
function renderComparison(){const c=current();$('prediction-result').hidden=!revealed;$('reveal-prediction').textContent=revealed?'Hide the example distribution':'Reveal the example distribution';const rows=[...c.next,['other tokens',100-c.next.reduce((s,[,p])=>s+p,0)]];$('compare-bars').innerHTML=bars(rows);const found=c.next.find(([w])=>w.toLowerCase()===prediction.toLowerCase());$('prediction-match').textContent=prediction?(found?`You proposed “${prediction}”. The scripted example assigns it ${found[1]}%.`:`You proposed “${prediction}”, outside the named shortlist. It may belong to the “other tokens” group; this demonstration cannot score it individually.`)+' A plausible continuation need not be the script’s chosen word.':`The script continues with “${c.target}”. Several alternatives may be plausible. You can still enter your own prediction; this is an illustration, not a model benchmark.`;}
$('prediction-form').addEventListener('submit',e=>{e.preventDefault();prediction=$('human-prediction').value.trim();$('prediction-feedback').textContent=prediction?`Your prediction: “${prediction}”. Now compare the illustration or revise your response.`:'Enter a word to record your prediction.';renderComparison();comparison?.refresh();});$('reveal-prediction').addEventListener('click',()=>{revealed=!revealed;renderComparison();});$$('[data-answer]').forEach(b=>b.addEventListener('click',()=>{$$('[data-answer]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('answer-feedback').textContent=b.dataset.answer==='1'?'Yes. A shared output supports a comparison of behavior, not an identity of mechanism. Neither attention weights nor your response are a brain measurement.':'A matching word does not establish a matching process. The papers describe different kinds of system at different explanatory levels.';}));
const socialCases={
 capture:{setting:'A prediction feed',interface:'<strong>Keep the streak alive.</strong><br>Choose the next word. A new prompt appears as soon as you finish.<br><span class="small">Suggested design: endless prompts, visible streak, engagement counters.</span>',incentive:'The service treats continued interaction as success.',action:'Submit and see the next prompt',feedback:'A hypothetical dashboard records a completion and offers another prompt. That trace would not tell it whether you understood the sentence.',details:[['Success','Return visits and continued interaction.'],['Visible trace','Clicks, completions, time in the activity.'],['Value & control','A platform controls ranking and the recorded traces; advertisers or owners may benefit.'],['Hidden activity','Understanding, fatigue, relevance and what the reader wanted to do instead.']],blindspot:'A measurable trace can become a commodity while missing the meaning and purpose of the activity that produced it.',synthesis:'A numerical system can rank what a reader sees; a reader’s orienting and control operate within that arrangement; the resulting clicks can become economic signals. Terranova asks how this organization makes attention appear scarce and exchangeable.'},
 assessment:{setting:'An individually graded exercise',interface:'<strong>Find the expected continuation.</strong><br>Your response is compared with one answer key.<br><span class="small">Suggested design: score, deadline, private submission.</span>',incentive:'The institution treats agreement with an answer key as success.',action:'Submit to the answer key',feedback:'The answer key returns a mark. A plausible alternative or a thoughtful explanation may remain invisible if only exact matches count.',details:[['Success','Agreement with the selected answer key.'],['Visible trace','A word, correctness mark and submission time.'],['Value & control','An instructor or institution defines the task, rubric and access to records.'],['Hidden activity','Reasoning, plausible alternatives, collaborative help and changes in understanding.']],blindspot:'An apparently neutral measure already contains a decision about what counts as learning. The choice of task organizes the reader’s attention.',synthesis:'The same predicted word changes meaning inside an assessment: it becomes evidence for an institutional judgment. A mechanism that computes probabilities and a network that supports task control do not explain who selected the rubric or whether it serves learning.'},
 cooperation:{setting:'A shared reading workshop',interface:'<strong>Offer a continuation and explain a clue.</strong><br>Compare two plausible readings. Build a shared annotation that others can revise.<br><span class="small">Suggested design: explanations, attribution, revision history, time to reflect.</span>',incentive:'The group values a useful shared interpretation, with disagreement visible.',action:'Add a reading to the shared discussion',feedback:'In this scenario your contribution becomes a revisable annotation. Nothing is actually posted or shared by this local demonstration.',details:[['Success','A more useful shared reading, including unresolved differences.'],['Visible trace','Contributions, explanations, attribution and revisions.'],['Value & control','The group needs explicit rules for access, moderation, credit and reuse.'],['Hidden activity','Silent learning, exclusion, unequal labor and who can participate at all.']],blindspot:'Cooperation can produce social value beyond individual scores. Its traces can still be captured or distributed unequally.',synthesis:'Through Tarde and Lazzarato, Terranova treats attention as involved in social production and invention. A shared annotation can extend memory and expectation beyond one reader. The question is how this activity is organized, supported and valued—not whether technology is simply good or bad.'}
};
function renderSocial(){const s=socialCases[social];$$('[data-social]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.social===social));$('social-setting').textContent=s.setting;$('social-prefix').innerHTML=prefixHTML();$('social-interface').innerHTML='<div class="social-preview">'+s.interface+'</div>';$('social-incentive').textContent=s.incentive;$('social-act').textContent='Show what gets recorded';$('social-act').setAttribute('aria-expanded','false');$('social-example').textContent='Example response: “'+current().target+'”. Imagine this reader submits it, with an explanation if the design asks for one.';$('social-details').innerHTML=s.details.map(([term,text])=>`<dt>${term}</dt><dd>${text}</dd>`).join('');$('social-blindspot').textContent=s.blindspot;$('social-synthesis').textContent=s.synthesis;}
$$('[data-social]').forEach(b=>b.addEventListener('click',()=>{social=b.dataset.social;$('social-feedback').textContent='';renderSocial();}));$('social-act').addEventListener('click',()=>{$('social-act').setAttribute('aria-expanded','true');$('social-feedback').textContent='Example receipt — '+socialCases[social].feedback+' Switch the organizer above to compare what counts. No response has been submitted.';});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopHuman();comparison?.setVisible(false);pauseFrames();brain?.setVisible(false);}else{brain?.setVisible(tab==='human');comparison?.setVisible(tab==='compare');}});
renderQuery();renderTraining();renderShared();renderChapterNavs();go(location.hash.slice(1)||'intro');
})();
