#!/usr/bin/env python3
"""Encode webp copies of the images the site serves, and repoint content at them.

Much of the image weight is generated section art: 2-3.5 MB PNGs of painterly,
grainy pictures, which is the content PNG compresses worst. Several course pages
weighed 20-50 MB. This script encodes a .webp beside each referenced master and
repoints the markdown at it. The PNG stays as the master, the way lecture 2's
slide art works (courses/479-fall-2026/_slides/lecture-2/encode-webp.py).

Which copy gets encoded
-----------------------
The same bytes often exist at both assets/images/<f> and courses/<id>/images/<f>,
and only one of them is ever served. Rather than guess, every reference is
resolved the way the website resolves it, and only what that reaches is encoded:

    /markdown/images/<f>              -> assets/images/<f>
        server.js mounts express.static on the content package's assets/images.

    images/<f> inside courses/<id>/   -> courses/<id>/images/<f>
        js/main.js rewrites relative refs in course content to
        /markdown/courses/<id>/images/, and standalone course HTML resolves
        them the same way relative to its own URL.

    images/<f> anywhere else          -> assets/images/<f>
        Non-course content gets the /markdown/images base instead.

Deriving the work-list this way means the unused duplicate is never encoded, and
the list stays correct as content moves between those reference forms.

Three rules keep it safe to re-run
----------------------------------
  * A reference is only rewritten when the .webp exists AND is meaningfully
    smaller. Small or already-efficient images keep their PNG rather than
    churning the markdown for nothing; a freshly encoded webp that misses the
    bar is deleted again, so it never reaches the repository.
  * References are scanned in both forms, so a .webp ref still resolves back to
    its master and gets re-encoded when that master changes. Without this the
    script would be one-shot - after the first pass there would be no .png refs
    left for it to find.
  * Up-to-date outputs are skipped, so re-running after regenerating a single
    image is cheap. --force re-encodes everything.

Hidden _* paths are scanned too, unlike ./build: drafts carry the section art
that is staged for lectures still being written, and encoding it now means the
webp is in place when those drafts are published.

Only .md is rewritten. The .html outputs are regenerated by ./build.

Usage:
    python3 assets/_tools/encode-webp.py            # encode + repoint
    python3 assets/_tools/encode-webp.py --dry-run  # report, change nothing
    python3 assets/_tools/encode-webp.py --force    # re-encode everything

Requires cwebp on PATH (brew install webp). No other dependencies.
"""

import collections
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
POOL = os.path.join("assets", "images")
CONTENT = ("articles", "courses", "notes")
QUALITY = "82"

# below this saving, leave the reference on the PNG - not worth the churn
MIN_SAVING = 0.25

MASTERS = (".png", ".jpeg", ".jpg")
RASTER = r"(?:png|jpe?g|webp)"

# Capture groups are (prefix, stem, extension) so a rewrite swaps only the
# extension and leaves the surrounding markdown syntax untouched.
ABS_RE = re.compile(rf"(/markdown/images/)([A-Za-z0-9._@%+-]+)\.({RASTER})\b", re.I)
REL_RE = re.compile(rf"(\]\(images/|src=[\"']images/)([A-Za-z0-9._@%+-]+)\.({RASTER})\b", re.I)


def markdown_files():
    for top in CONTENT:
        for dirpath, dirnames, filenames in os.walk(os.path.join(ROOT, top)):
            dirnames[:] = [d for d in dirnames if d != "node_modules"]
            for name in sorted(filenames):
                if name.endswith(".md"):
                    yield os.path.relpath(os.path.join(dirpath, name), ROOT)


def image_dir(relfile, ref_is_absolute):
    """The directory a reference in relfile resolves against."""
    parts = relfile.split(os.sep)
    if not ref_is_absolute and parts[0] == "courses" and len(parts) > 2:
        return os.path.join("courses", parts[1], "images")
    return POOL


def master_for(directory, stem, ext):
    """Repo-relative master for a reference, resolving .webp back to its source."""
    if ext.lower() == "webp":
        for candidate in MASTERS:
            path = os.path.join(directory, stem + candidate)
            if os.path.exists(os.path.join(ROOT, path)):
                return path
        return None
    return os.path.join(directory, f"{stem}.{ext}")


def referenced():
    """Map master path -> set of .md files referencing it, in either form."""
    found = collections.defaultdict(set)
    for relfile in markdown_files():
        with open(os.path.join(ROOT, relfile), encoding="utf-8", errors="ignore") as fh:
            text = fh.read()
        for regex, is_abs in ((ABS_RE, True), (REL_RE, False)):
            for match in regex.finditer(text):
                master = master_for(image_dir(relfile, is_abs),
                                    match.group(2), match.group(3))
                if master:
                    found[master].add(relfile)
    return found


def encode(masters, force, dry_run):
    """Return {master path: webp path} for masters whose webp is worth using."""
    wins, saved, skipped, missing = {}, 0, [], []
    for master in sorted(masters):
        full = os.path.join(ROOT, master)
        if not os.path.exists(full):
            missing.append(master)
            continue
        webp = os.path.splitext(master)[0] + ".webp"
        out = os.path.join(ROOT, webp)
        stale = (not os.path.exists(out)
                 or os.path.getmtime(out) < os.path.getmtime(full))
        if (stale or force) and not dry_run:
            subprocess.run(["cwebp", "-quiet", "-q", QUALITY, full, "-o", out],
                           check=True)
        if not os.path.exists(out):
            continue  # dry run with nothing encoded yet
        big, small = os.path.getsize(full), os.path.getsize(out)
        if 1 - small / big < MIN_SAVING:
            skipped.append((master, big, small))
            if not dry_run and stale:
                os.remove(out)
            continue
        wins[master] = webp
        saved += big - small
    return wins, saved, skipped, missing


def repoint(wins, dry_run):
    """Point every reference at its webp. Returns the .md files changed."""
    changed = []
    for relfile in markdown_files():
        path = os.path.join(ROOT, relfile)
        with open(path, encoding="utf-8") as fh:
            original = fh.read()

        def swap(match, is_abs):
            prefix, stem, ext = match.group(1), match.group(2), match.group(3)
            master = master_for(image_dir(relfile, is_abs), stem, ext)
            if master in wins:
                return f"{prefix}{stem}.webp"
            return match.group(0)

        text = ABS_RE.sub(lambda m: swap(m, True), original)
        text = REL_RE.sub(lambda m: swap(m, False), text)
        if text != original:
            changed.append(relfile)
            if not dry_run:
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(text)
    return changed


def page_report(found, wins, limit=8):
    """Image bytes each page pulls, before and after."""
    weight = collections.defaultdict(lambda: [0, 0])
    for master, refs in found.items():
        full = os.path.join(ROOT, master)
        if not os.path.exists(full):
            continue
        big = os.path.getsize(full)
        out = os.path.join(ROOT, wins[master]) if master in wins else None
        small = os.path.getsize(out) if out and os.path.exists(out) else big
        for ref in refs:
            weight[ref][0] += big
            weight[ref][1] += small
    rows = sorted(weight.items(), key=lambda kv: kv[1][0], reverse=True)[:limit]
    if rows:
        print("\nHeaviest pages (image bytes only):")
        for ref, (big, small) in rows:
            print(f"  {big / 1048576:6.1f} MB -> {small / 1048576:5.1f} MB   {ref}")


def main():
    force = "--force" in sys.argv[1:]
    dry_run = "--dry-run" in sys.argv[1:]
    if not shutil.which("cwebp"):
        sys.exit("cwebp not found on PATH (brew install webp)")

    found = referenced()
    pool = sum(1 for m in found if m.startswith(POOL))
    print(f"{len(found)} images referenced by content "
          f"({pool} in {POOL}, {len(found) - pool} in course image folders)")

    wins, saved, skipped, missing = encode(found, force, dry_run)

    for master in missing:
        print(f"  referenced but not on disk: {master}")
    for master, big, small in skipped:
        print(f"  {master}: webp saves only "
              f"{100 * (1 - small / big):.0f}%, keeping the PNG")

    changed = repoint(wins, dry_run)
    verb = "would repoint" if dry_run else "repointed"
    print(f"\n{len(wins)} images encoded, {saved / 1048576:.1f} MB saved\n"
          f"{verb} {len(changed)} markdown files")
    for relfile in changed[:12]:
        print(f"  {relfile}")
    if len(changed) > 12:
        print(f"  ... and {len(changed) - 12} more")
    if changed and not dry_run:
        print("\nRun ./build to regenerate the .html outputs.")

    page_report(found, wins)


if __name__ == "__main__":
    main()
