#!/usr/bin/env bash
# Shared loader for the content-owned render exclusion manifest.
# Source this file, then call load_render_exclusions before render_excluded.
#
# A render exclusion marks a .md whose sibling .html is the real source: the
# page is hand-authored, or generated by a publisher outside this repository.
# The .md exists only to give /essays its index metadata. ./build must never
# Pandoc-render over such a page.
#
# Unlike the essay manifest, an entry-less manifest is valid: a repository with
# no hand-authored pages legitimately excludes nothing.

RENDER_EXCLUSION_PATTERNS=()

load_render_exclusions() {
  local manifest="${1:-config/render-exclusions.txt}"
  local line line_no=0

  if [ ! -f "$manifest" ]; then
    echo "render exclusions: manifest not found: $manifest" >&2
    return 1
  fi

  RENDER_EXCLUSION_PATTERNS=()
  while IFS= read -r line || [ -n "$line" ]; do
    line_no=$((line_no + 1))
    case "$line" in
      ""|\#*) continue ;;
    esac
    if [[ "$line" =~ [[:space:]] ]] || [[ ! "$line" =~ ^[A-Za-z0-9._*/-]+$ ]] \
      || [[ "$line" == /* ]] || [[ "$line" == *".."* ]]; then
      echo "render exclusions: malformed pattern at $manifest:$line_no: $line" >&2
      return 1
    fi
    RENDER_EXCLUSION_PATTERNS+=("$line")
  done < "$manifest"
}

# Match against a source path relative to the repository root, e.g.
# articles/ai-tutor/geist-atlas.md
render_excluded() {
  local src="${1#./}"
  local pattern
  for pattern in "${RENDER_EXCLUSION_PATTERNS[@]:-}"; do
    [ -n "$pattern" ] || continue
    [[ "$src" == $pattern ]] && return 0
  done
  return 1
}
