// Browser checks for the fourteen-screen journey (the entry page). Set ATTENTION_PLAYWRIGHT_MODULE / ATTENTION_QA_DIR as needed.
const {chromium}=require(process.env.ATTENTION_PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),http=require('http');
const root=path.resolve(__dirname,'..'),qa=process.env.ATTENTION_QA_DIR;const types={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.bin':'application/octet-stream'};
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));fs.readFile(file,(err,body)=>{res.writeHead(err?404:200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(body);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
for(const [name,vp] of [['desktop',{width:1440,height:900}],['mobile',{width:390,height:844}]]){const page=await browser.newPage({viewport:vp,reducedMotion:'reduce'});const errors=[],failed=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push(r.url());});
await page.goto(origin+'/spotlight-attention-game.html');await page.locator('#s0.on').waitFor();
const shot=async n=>{if(!qa)return;await page.screenshot({path:path.join(qa,`${name}-${n}.png`),fullPage:true});};const overflow=async n=>{assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow ${name} ${n}`);};
await page.locator('#chips0 [data-w="tired"]').click();assert.match(await page.locator('#say0').textContent(),/27/);await shot(0);await overflow(0);
await page.locator('#next').click();await page.locator('#s1.on').waitFor();await page.waitForTimeout(250);assert.ok(await page.locator('#words1 svg path').count()>=2);await page.locator('#words1 button[data-j="1"]').click();assert.match(await page.locator('#say1').textContent(),/cat/);await shot(1);await overflow(1);
await page.locator('#next').click();await page.locator('#s2.on').waitFor();await page.locator('#step2').click();await page.locator('#step2').click();await page.waitForTimeout(150);assert.ok(await page.locator('#words2 .w').count()>5);await page.locator('#step2').click();assert.ok(await page.locator('#bars2 .bar').count()>=4);await page.locator('#play2').click();await page.waitForTimeout(300);await page.locator('#play2').click();await shot(2);await overflow(2);
// Detail opens the full lab, in embed mode and dark, at the chapter behind this screen; Escape closes it.
assert.match(await page.locator('#detail').textContent(),/The paper and the idea/);await page.locator('#detail').click();await page.locator('#drawer.open').waitFor();const lab=page.frameLocator('#drawer-frame');await lab.locator('#paper:not([hidden])').waitFor();assert.equal(await lab.locator('.masthead').isVisible(),false);assert.equal(await lab.locator('html').getAttribute('data-theme'),'dark');assert.equal(await lab.locator('#paper .primer').isVisible(),true);await shot('2-detail');await page.keyboard.press('Escape');await page.waitForFunction(()=>document.getElementById('drawer').hidden);assert.equal(await page.locator('#s2.on').count(),1);
await page.locator('#next').click();await page.locator('#s3.on').waitFor();for(let i=0;i<3;i++)await page.locator('#words3 button[data-j="1"]').click();assert.match(await page.locator('#say3').textContent(),/attention weight/);await shot(3);await overflow(3);
await page.locator('#next').click();await page.locator('#s4.on').waitFor();await page.locator('#chips4 [data-tag="thing"]').click();assert.match(await page.locator('#say4').textContent(),/mat/);await page.locator('#chips4 [data-tag="thing"]').click();await page.locator('#chips4 [data-tag="animal"]').click();assert.match(await page.locator('#say4').textContent(),/cat wins/);await shot(4);await overflow(4);
await page.locator('#next').click();await page.locator('#s5.on').waitFor();assert.equal(await page.locator('#blend5 .cell').count(),4);await shot(5);await overflow(5);
await page.locator('#next').click();await page.locator('#s6.on').waitFor();for(let i=0;i<8;i++)await page.locator('#nudge6').click();assert.match(await page.locator('#say6').textContent(),/billions/);await shot(6);await overflow(6);
await page.locator('#next').click();await page.locator('#s7.on').waitFor();await shot(7);await overflow(7);
await page.locator('#next').click();await page.locator('#s8.on').waitFor();await page.locator('#sys8 [data-g="exec"]').click();assert.match(await page.locator('#say8').textContent(),/Executive/);assert.equal(await page.locator('#g-exec').getAttribute('class'),'g on');await shot(8);await overflow(8);
await page.locator('#next').click();await page.locator('#s9.on').waitFor();await page.locator('#play9').click();await page.waitForTimeout(400);assert.equal(await page.locator('#you9 li.on').count(),4);await shot(9);await overflow(9);
await page.locator('#next').click();await page.locator('#s10.on').waitFor();await shot(10);await overflow(10);
await page.locator('#next').click();await page.locator('#s11.on').waitFor();assert.equal(await page.locator('#crowd11 i').count(),100);
// A second Detail reuses the loaded lab and jumps to the social chapter.
await page.locator('#detail').click();await page.locator('#drawer.open').waitFor();await page.frameLocator('#drawer-frame').locator('#social:not([hidden])').waitFor();assert.equal(await page.frameLocator('#drawer-frame').locator('#pg-brief').isVisible(),true);await page.locator('#drawer-close').click();await page.waitForFunction(()=>document.getElementById('drawer').hidden);
for(const mv of ['boost','interrupt','boost']){await page.locator(`#moves11 [data-move="${mv}"]`).click();await page.locator('#go11').click();await page.waitForFunction(()=>/opened/.test(document.getElementById('result11').textContent));if(mv!=='boost'||true)await page.waitForTimeout(150);}
await shot(11);await overflow(11);await page.locator('#s12.on').waitFor({timeout:5000});const money=parseInt(await page.locator('#b-money').textContent());console.log(name,'money',money,'title',await page.locator('#title12').textContent());await shot(12);await overflow(12);
await page.locator('#next').click();await page.locator('#s13.on').waitFor();await shot(13);await overflow(13);
await page.keyboard.press('Home');await page.locator('#s0.on').waitFor();await page.goto(origin+'/spotlight-attention-game.html#s8');await page.locator('#s8.on').waitFor();
const legacy=await browser.newPage();await legacy.goto(origin+'/spotlight-attention-game.html#social');await legacy.waitForURL(/spotlight-attention-lab\.html#social/);await legacy.locator('#social:not([hidden])').waitFor();await legacy.close();
if(name==='desktop'){const plain=await browser.newPage();await plain.goto(origin+'/spotlight-attention-game.html?detail=0');await plain.locator('#s0.on').waitFor();assert.equal(await plain.locator('#detail').isVisible(),false);await plain.close();}
console.log(JSON.stringify({name,errors,failed}));await page.close();}
await browser.close();server.close();})().catch(e=>{console.error(e);process.exit(1);});
