// Browser regression checks for the course introduction, four perspectives and retained games.
// Set ATTENTION_PLAYWRIGHT_MODULE / ATTENTION_BROWSER_EXECUTABLE when needed.
const {chromium}=require(process.env.ATTENTION_PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..');
const types={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.png':'image/png','.css':'text/css','.json':'application/json','.bin':'application/octet-stream'};
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,body)=>{res.writeHead(err?404:200,{'Content-Type':types[path.extname(file)]||'text/plain'});res.end(err?'missing':body);});});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
 const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader'],...(process.env.ATTENTION_BROWSER_EXECUTABLE?{executablePath:process.env.ATTENTION_BROWSER_EXECUTABLE}:{})});
 try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const page=await context.newPage(),errors=[],external=[],failed=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(origin))external.push(r.url());});page.on('response',r=>{if(r.status()>=400)failed.push([r.status(),r.url()]);});
 await page.goto(origin+'/spotlight-attention-lab.html');await page.locator('#intro').waitFor();assert.equal(await page.locator('#tab-intro').getAttribute('aria-current'),'page');assert.equal(await page.locator('#chapter-rail [data-go]').count(),11);assert.equal(await page.locator('#paper').isVisible(),false);assert.equal(await page.locator('#shared-reading').isVisible(),false);assert.ok(page.url().endsWith('#intro'));assert.match(await page.locator('#week-intro-title').textContent(),/Different kinds/);await page.waitForFunction(()=>document.querySelector('.opening-image img').naturalWidth===1536);assert.match(await page.locator('#opening-title').textContent(),/What is/);assert.equal(await page.locator('.how-to .card').count(),3);if(process.env.ATTENTION_QA_DIR){await page.locator('#framing').screenshot({path:path.join(process.env.ATTENTION_QA_DIR,'editorial-opening-desktop.png')});}
 await page.locator('.opening-actions [data-go="paper"]').click();assert.equal(await page.locator('#intro').isVisible(),false);assert.equal(await page.locator('#paper').isVisible(),true);assert.equal(await page.locator('#shared-reading').isVisible(),true);assert.match(await page.locator('#paper .primer').textContent(),/Vaswani/);assert.equal(await page.locator('#paper .todo li').count(),3);await page.locator('#paper [data-nav] .primary').click();assert.equal(await page.locator('#queries').isVisible(),true);assert.equal(await page.locator('#tab-paper').getAttribute('class'),'visited');await page.locator('.wordmark').click();await page.locator('#intro').waitFor();for(const section of ['compare','social','paper','human']){await page.locator('#route-map [data-go="'+section+'"]').click();assert.equal(await page.locator('#'+section).isVisible(),true);await page.locator('#tab-intro').click();}await page.locator('#tab-practice').click();
 const game=page.frameLocator('#games-frame'),introGame=page.frameLocator('#intro-frame');await game.locator('[data-level="7"]').waitFor();assert.equal(await game.locator('[data-level]').count(),7);assert.match(await game.locator('#intro').textContent(),/Level 1/);
 // All six preserved levels, sixteen puzzles, and normalized attention at all rows.
 const gf=page.frames().find(f=>f.url().includes('spotlight-machine.html?view=levels'));
 const inventory=await gf.evaluate(()=>LEVELS.map(l=>({id:l.id,mode:l.mode,count:l.puzzles.length})));assert.deepEqual(inventory.map(l=>l.count),[0,2,6,2,2,3,1,0]);
 let puzzles=0;
 for(let level=1;level<=6;level++){
  await game.locator(`[data-level="${level}"]`).click();assert.ok((await game.locator('#intro').textContent()).includes('Level '+level));
  const results=await gf.evaluate(level=>LEVELS[level].puzzles.map((_,p)=>{goTo(level,p);const r=compute();return {rows:(r.heads||r.rows||r.layers.flatMap(x=>[{w:x.w1},{w:x.w2}])).map(x=>x.w),score:evaluate(r).match};}),level);
  results.forEach(r=>{puzzles++;r.rows.forEach(row=>{assert.ok(row.every(Number.isFinite));assert.ok(Math.abs(row.reduce((s,w)=>s+w,0)-1)<1e-10);});assert.ok(Number.isFinite(r.score));});
 }
 // Real controls change calculations, unlock completion, and reset the board.
 await game.locator('[data-level="1"]').click();for(let i=0;i<5;i++)await game.locator('[data-act="step"][data-i="1"][data-d="1"]').click();assert.equal(await game.locator('[data-next]').isEnabled(),true);await game.locator('[data-next]').click();assert.match(await game.locator('[data-msg]').textContent(),/./);await game.locator('[data-act="reset"]').click();
 await game.locator('[data-level="2"]').click();await game.locator('[data-act="chip"][data-f="ANIMATE"][data-d="1"]').click();assert.equal(await gf.evaluate(()=>state.q[0].ANIMATE),1);
 await game.locator('[data-level="3"]').click();await game.locator('#scale').fill('2');assert.equal(await gf.evaluate(()=>state.scale),2);
 await game.locator('[data-level="4"]').click();await game.locator('[data-act="chip"][data-h="1"][data-f="VERB"][data-d="1"]').click();assert.equal(await gf.evaluate(()=>state.q[1].VERB),1);
 await game.locator('[data-level="5"]').click();await game.locator('select[data-set="rules"][data-k="if"]').first().selectOption('PRON');await game.locator('select[data-set="rules"][data-k="look"]').first().selectOption('NOUN');assert.ok(await game.locator('.heat .cell[aria-label]').count()>0);
 await game.locator('[data-level="6"]').click();assert.equal(await game.locator('[data-forge]').count(),2);await game.locator('[data-act="radd"][data-set="rules1"]').click();assert.equal(await gf.evaluate(()=>state.rules1.length),2);
 await game.locator('[data-level="7"]').click();await game.locator('#sbSentence').selectOption('bankRiver');assert.equal(await gf.evaluate(()=>state.sbSentence),'bankRiver');
 // Query origin: position and projection affect numbers independently.
 await page.locator('#tab-queries').click();const q1=await page.locator('#q-math').textContent();await page.locator('#q-position').selectOption('1');assert.notEqual(await page.locator('#q-math').textContent(),q1);await page.locator('#q-position').selectOption('0');assert.equal(await page.locator('#q-math').textContent(),q1);await page.locator('#q-weight').fill('1.8');assert.notEqual(await page.locator('#q-math').textContent(),q1);await page.locator('#q-reset').click();assert.equal(await page.locator('#q-math').textContent(),q1);
 // A real optimizer step lowers loss; inference preserves parameters and count.
 await page.locator('#tab-training').click();let loss=+(await page.locator('#loss').textContent());
 const theta0=.15,z0=Math.tanh(theta0),p0=1/(1+Math.exp(-4*z0)),expectedTheta=theta0-.15*4*(p0-1)*(1-z0*z0);
 await page.locator('#learn-once').click();assert.ok(Math.abs(+(await page.locator('#theta').textContent())-expectedTheta)<.00051);
 for(let i=0;i<8;i++){await page.locator('#learn-once').click();const next=+(await page.locator('#loss').textContent());assert.ok(next<loss);loss=next;}
 const theta=await page.locator('#theta').textContent(),count=await page.locator('#updates').textContent();await page.locator('#mode-infer').click();await page.locator('#infer-once').click();assert.equal(await page.locator('#theta').textContent(),theta);assert.equal(await page.locator('#updates').textContent(),count);assert.equal(await page.locator('#loss').textContent(),'—');
 // Retained inspector: every head/query/mask combination, one shared key matrix.
 await page.locator('#tab-numbers').click();const numeric=page.frameLocator('#vectors-frame');await numeric.locator('#cat-share').waitFor();const nf=page.frames().find(f=>f.url().endsWith('vector-lab.html'));
 const numerical=[];
 for(const mask of [false,true]){await numeric.locator('#causal').setChecked(mask);for(let h=0;h<8;h++){await numeric.locator('#head').selectOption(String(h));for(let q=0;q<7;q++){await numeric.locator(`[data-query="${q}"]`).click();const data=await nf.evaluate(()=>({weights:[...document.querySelectorAll('[data-weight]')].map(e=>+e.dataset.weight),rows:[...document.querySelectorAll('#matrix tbody tr')].map(r=>[...r.querySelectorAll('td')].map(c=>+c.dataset.matrixWeight))}));numerical.push({mask,h,q,...data});}}}

 for(const c of numerical){assert.ok(Math.abs(c.weights.reduce((a,b)=>a+b,0)-1)<1e-12);if(c.mask)assert.ok(c.weights.slice(c.q+1).every(v=>v===0));c.weights.forEach((v,i)=>assert.ok(Math.abs(v-c.rows[c.q][i])<1e-12));c.rows.forEach((r,i)=>{assert.ok(Math.abs(r.reduce((a,b)=>a+b,0)-1)<1e-12);if(c.mask)assert.ok(r.slice(i+1).every(v=>v===0));});}
 await numeric.locator('#machine-reset').click();await numeric.locator('[data-step="2"]').click();assert.match(await numeric.locator('#machine-caption').textContent(),/\[0.79, 0.30\]/);
 await numeric.locator('#boost').fill('3');assert.ok(parseFloat(await numeric.locator('#cat-share').textContent())>71);
 // Shared prefix and exact scripted distribution remain identical in all views.
 for(const key of ['cat','glass','machines']){
  await page.locator('#reading-case').selectOption(key);await page.locator('#tab-paper').click();await introGame.locator('[data-demo="step"]').waitFor();assert.equal(await introGame.locator('#levelNav').isVisible(),false);await page.locator('#demo-shared').click();await introGame.locator('[data-demo="step"]').click();await introGame.locator('[data-demo="step"]').click();
  const displayed=await introGame.locator('.dtok:not(.ghost) .word').allTextContents();const prefix=(await page.locator('#shared-prefix').textContent()).replace(/\s*…$/,'').trim();assert.equal(displayed.join(' '),prefix);
  const pred=await introGame.locator('.pred-row .pp').allTextContents();await page.locator('#tab-compare').click();await page.locator('#human-prediction').fill(key==='cat'?'tired':'test');await page.locator('#prediction-form button').click();await page.locator('#reveal-prediction').click();const values=await page.locator('#compare-bars [data-probability]').evaluateAll(es=>es.map(e=>+e.dataset.probability));assert.deepEqual(values,pred.map(parseFloat));assert.equal(values.reduce((a,b)=>a+b,0),100);assert.equal(await page.locator('#human-sentence').textContent(),await page.locator('#shared-prefix').textContent());await page.locator('#tab-paper').click();
 }
 // The anatomical WebGL renderer really loads and changes pixels across networks.
 await page.locator('#tab-human').click();await page.locator('#brain-status[data-ready="true"]').waitFor({timeout:30000});await page.waitForFunction(()=>document.getElementById('brain').dataset.triangles==='40960');
 let lastImage='';for(let i=0;i<5;i++){await page.locator(`button[data-moment="${i}"]`).click();await page.waitForFunction(i=>document.getElementById('brain').dataset.moment===String(i),i);assert.ok(await page.locator('#region-list li').count()>=2);const img=await page.locator('#brain').evaluate(c=>c.toDataURL());assert.notEqual(img,lastImage);lastImage=img;}
 const rotation=await page.locator('#brain').getAttribute('data-rotation');await page.locator('#rotate-left').click();await page.waitForFunction(r=>document.getElementById('brain').dataset.rotation!==r,rotation);await page.locator('#brain').press('Home');assert.equal(await page.locator('#brain-opacity').inputValue(),'50');await page.locator('#brain-opacity').fill('20');await page.waitForFunction(()=>document.getElementById('brain').dataset.opacity==='0.20');await page.locator('#hemisphere').selectOption('left');await page.locator('#hemisphere').selectOption('both');await page.locator('#brain-opacity').fill('100');await page.waitForFunction(()=>document.getElementById('brain').dataset.opacity==='1.00');await page.locator('#brain-opacity').fill('50');for(const [system,name] of [[0,'Alerting'],[1,'Orienting'],[3,'Executive control']]){await page.locator(`[data-system="${system}"]`).click();assert.equal(await page.locator('#brain-system-title').textContent(),name);assert.match(await page.locator('#regions-title').textContent(),new RegExp(name.toLowerCase()));}
 // The human memory panel follows the same scene controls and selected sentence.
 for(const [scene,mode] of [[0,'hold'],[2,'refresh'],[3,'hold'],[4,'check']]){await page.locator(`button[data-moment="${scene}"]`).click();assert.equal(await page.locator('#human-reading-memory').getAttribute('data-memory-mode'),mode);assert.match(await page.locator('#human-reading-memory .memory-goal').textContent(),/Predict the next word/);}
 await page.locator('#reading-case').selectOption('glass');assert.match(await page.locator('#human-reading-memory [data-memory-gist]').textContent(),/glass/);assert.match(await page.locator('#human-memory-explainer').textContent(),/Maintaining a task is not the same as storing its content/);
 // Region lights retain their brightness when only the cortical shell fades.
 const brightPixels=id=>page.locator(id).evaluate(c=>{const surface=document.createElement('canvas');surface.width=c.width;surface.height=c.height;const ctx=surface.getContext('2d');ctx.fillStyle='#171717';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(c,0,0);const pixels=ctx.getImageData(0,0,c.width,c.height).data;let bright=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i]>190)bright++;return bright;});
 for(const network of [0,1,2,3,4]){await page.locator(`button[data-moment="${network}"]`).click();await page.waitForFunction(i=>document.getElementById('brain').dataset.moment===String(i),network);await page.locator('#brain-opacity').fill('50');await page.waitForFunction(()=>document.getElementById('brain').dataset.opacity==='0.50');const normal=await brightPixels('#brain');await page.locator('#brain-opacity').fill('10');await page.waitForFunction(()=>document.getElementById('brain').dataset.opacity==='0.10');const faint=await brightPixels('#brain');assert.ok(faint>100,`network ${network} has visible highlights at 10%`);assert.ok(faint>=normal*.8,`network ${network} keeps its highlights: ${normal} at 50%, ${faint} at 10%`);}
 await page.locator('#brain-opacity').fill('50');
 await page.locator('button[data-moment="0"]').click();await page.clock.install();await page.locator('#human-play').click();await page.clock.fastForward(6100);assert.match(await page.locator('#human-progress').textContent(),/Moment 2/);await page.locator('#human-play').click();await page.clock.fastForward(7000);assert.match(await page.locator('#human-progress').textContent(),/Moment 2/);await page.clock.resume();
 // The shared reading really advances words, computes causal attention, and
 // animates within each word rather than merely switching explanatory slides.
 await page.locator('#tab-compare').click();await page.locator('#comparison-seek').waitFor();
 await page.waitForFunction(()=>document.getElementById('compare-brain').dataset.triangles==='40960');
 for(const key of ['cat','glass','machines']){
  await page.locator('#reading-case').selectOption(key);assert.equal(await page.locator('#comparison-player').getAttribute('data-word'),'0');
  const last=+(await page.locator('#comparison-seek').getAttribute('max'));
  for(let index=0;index<=last;index++){
   await page.locator('#comparison-seek').fill(String(index));
   assert.equal(await page.locator('#comparison-human-tokens [aria-current="step"]').getAttribute('data-reading-word'),String(index));assert.equal(await page.locator('#comparison-machine-tokens [aria-current="step"]').getAttribute('data-reading-word'),String(index));
   const weights=await page.locator('.reading-key-node').evaluateAll(es=>es.map(e=>+e.dataset.weight));assert.ok(Math.abs(weights.reduce((a,b)=>a+b,0)-1)<1e-12);assert.ok(weights.slice(index+1).every(w=>w===0));
   assert.equal(await page.locator('#comparison-human-tokens').textContent(),await page.locator('#comparison-machine-tokens').textContent());
   assert.equal(await page.locator('#comparison-human-memory').getAttribute('data-word'),String(index));assert.equal(await page.locator('#comparison-machine-memory .available').count(),index+1);assert.equal(await page.locator('#comparison-machine-memory .unavailable').count(),last-index);assert.match(await page.locator('#comparison-human-memory .memory-goal').textContent(),/Predict the next word/);
   if(key==='glass'&&index===3)assert.doesNotMatch(await page.locator('#comparison-human-memory [data-memory-gist]').textContent(),/fragile/);if(key==='glass'&&index===4)assert.match(await page.locator('#comparison-human-memory [data-memory-gist]').textContent(),/fragile/);
  }
  if(key==='glass'){assert.equal(await page.locator('#comparison-human-tokens .reading-return').textContent(),'glass');}
  // Continue through representation → vocabulary scores → softmax → choice.
  await page.locator('#comparison-next').click();assert.equal(await page.locator('#comparison-player').getAttribute('data-predicting'),'true');assert.equal(await page.locator('.vocabulary-row').count(),6);assert.match(await page.locator('.prediction-operation').textContent(),/word scores/);
  await page.locator('#comparison-next').click();assert.match(await page.locator('.prediction-operation').textContent(),/probabilities/);assert.equal(await page.locator('[data-next-token]').count(),0);
  await page.locator('#comparison-next').click();const ending={cat:'tired',glass:'carefully',machines:'context'}[key];assert.equal(await page.locator('[data-next-token="human"]').textContent(),ending);assert.equal(await page.locator('[data-next-token="machine"]').textContent(),ending);assert.equal(await page.locator('.vocabulary-winner').getAttribute('data-vocabulary-word'),ending);assert.equal(await page.locator('#comparison-human-memory').getAttribute('data-memory-mode'),'check');assert.equal(await page.locator('#comparison-machine-memory .available').count(),last+1);
  await page.locator('#comparison-next').click();assert.equal(await page.locator('#comparison-player').getAttribute('data-complete'),'true');
  const values=await page.locator('#comparison-output-bars [data-probability]').evaluateAll(es=>es.map(e=>+e.dataset.probability));assert.equal(values.length,6);assert.ok(Math.abs(values.reduce((s,n)=>s+n,0)-100)<1e-10);
  assert.match(await page.locator('#comparison-machine-result').textContent(),new RegExp(ending));assert.equal(await page.locator('#comparison-output').isVisible(),true);
  // The original scripted distribution is still separately available below.
  assert.equal(await page.locator('#compare-bars [data-probability]').count(),5);
 }
 await page.locator('#compare-opacity').fill('25');assert.equal(await page.locator('#brain-opacity').inputValue(),'25');await page.waitForFunction(()=>document.getElementById('compare-brain').dataset.opacity==='0.25');await page.locator('#compare-opacity').fill('50');
 await page.locator('#reading-case').selectOption('cat');await page.locator('#comparison-seek').fill('7');assert.equal(await page.locator('#comparison-human-tokens .reading-return').textContent(),'cat');
 await page.clock.pauseAt(await page.evaluate(()=>Date.now()+60000));
 await page.locator('#comparison-reset').click();await page.locator('#comparison-play').click();await page.clock.runFor(1800);assert.equal(await page.locator('#comparison-player').getAttribute('data-phase'),'1');await page.clock.runFor(2500);assert.equal(await page.locator('#comparison-player').getAttribute('data-word'),'1');
 await page.locator('#comparison-play').click();const stopped=await page.locator('#comparison-player').getAttribute('data-progress');await page.clock.runFor(4500);assert.equal(await page.locator('#comparison-player').getAttribute('data-progress'),stopped);
 await page.locator('#comparison-play').click();await page.locator('#tab-human').click();await page.clock.runFor(4500);assert.equal(await page.locator('#comparison-player').getAttribute('data-word'),'1');
 await page.locator('#tab-compare').click();await page.locator('#comparison-seek').fill('8');await page.locator('#comparison-play').click();await page.clock.runFor(3000);assert.equal(await page.locator('#comparison-player').getAttribute('data-predicting'),'true');assert.equal(await page.locator('#comparison-player').getAttribute('data-prediction-phase'),'0');await page.clock.runFor(12500);assert.equal(await page.locator('#comparison-player').getAttribute('data-complete'),'true');assert.equal(await page.locator('#comparison-output').isVisible(),true);assert.equal(await page.locator('#comparison-player').getAttribute('data-playing'),'false');await page.locator('#comparison-reset').click();assert.match(await page.locator('#comparison-play').textContent(),/Read together/);
 // Confirm actual motion inside a word, not just a changed caption.
 await page.emulateMedia({reducedMotion:'no-preference'});await page.locator('#comparison-seek').fill('7');await page.locator('#comparison-play').click();await page.clock.runFor(100);
 const packetBefore=await page.locator('[data-packet="1"]').getAttribute('cx'),brainBefore=await page.locator('#compare-brain').evaluate(c=>c.toDataURL());await page.clock.runFor(400);
 assert.notEqual(await page.locator('[data-packet="1"]').getAttribute('cx'),packetBefore);assert.notEqual(await page.locator('#compare-brain').evaluate(c=>c.toDataURL()),brainBefore);await page.locator('#comparison-play').click();const packetPaused=await page.locator('[data-packet="1"]').getAttribute('cx');await page.clock.runFor(400);assert.equal(await page.locator('[data-packet="1"]').getAttribute('cx'),packetPaused);await page.emulateMedia({reducedMotion:'reduce'});
 // The human page animates inside a scene, pauses completely, and can resume
 // its countdown. Reduced motion keeps the lights static while time advances.
 await page.emulateMedia({reducedMotion:'no-preference'});await page.locator('#tab-human').click();await page.locator('button[data-moment="0"]').click();await page.locator('#brain-opacity').fill('10');await page.clock.runFor(100);await page.locator('#human-stage-play').click();await page.clock.runFor(250);
 const humanPixels=await page.locator('#brain').evaluate(c=>c.toDataURL()),humanProgress=+(await page.locator('.human-timeline').getAttribute('aria-valuenow'));await page.clock.runFor(600);
 assert.notEqual(await page.locator('#brain').evaluate(c=>c.toDataURL()),humanPixels);assert.ok(+(await page.locator('.human-timeline').getAttribute('aria-valuenow'))>humanProgress);assert.equal(await page.locator('#human-playback-state').textContent(),'Playing');assert.equal(await page.locator('#brain').getAttribute('data-moment'),'0');
 await page.locator('#human-stage-play').click();await page.clock.runFor(100);const pausedHuman=await page.locator('#brain').evaluate(c=>c.toDataURL()),pausedProgress=await page.locator('.human-timeline').getAttribute('aria-valuenow');await page.clock.runFor(700);assert.equal(await page.locator('#brain').evaluate(c=>c.toDataURL()),pausedHuman);assert.equal(await page.locator('.human-timeline').getAttribute('aria-valuenow'),pausedProgress);assert.equal(await page.locator('#human-playback-state').textContent(),'Paused');
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#human-play').click();await page.clock.runFor(100);const stillHuman=await page.locator('#brain').evaluate(c=>c.toDataURL());await page.clock.runFor(600);assert.equal(await page.locator('#brain').evaluate(c=>c.toDataURL()),stillHuman);assert.ok(+(await page.locator('.human-timeline').getAttribute('aria-valuenow'))>+pausedProgress);
 await page.locator('#tab-compare').click();await page.clock.runFor(100);assert.equal(await page.locator('#human-playback-state').textContent(),'Paused');assert.ok(await brightPixels('#compare-brain')>100);await page.locator('#compare-opacity').fill('50');
 await page.locator('#tab-human').click();await page.locator('button[data-moment="4"]').click();await page.locator('#human-stage-play').click();await page.clock.runFor(6100);assert.equal(await page.locator('#human-playback-state').textContent(),'Sequence complete');await page.locator('#human-stage-play').click();await page.clock.runFor(100);assert.equal(await page.locator('#brain').getAttribute('data-moment'),'0');await page.locator('#human-play').click();
 await page.clock.resume();
 // Prediction shortcut, pause, reverse stepping and context reset are usable.
 await page.locator('#tab-compare').click();await page.locator('#comparison-predict').click();assert.equal(await page.locator('#comparison-player').getAttribute('data-predicting'),'true');assert.equal(await page.locator('#comparison-player').getAttribute('data-playing'),'true');await page.locator('#comparison-play').click();await page.locator('#comparison-next').click();assert.equal(await page.locator('#comparison-player').getAttribute('data-prediction-phase'),'1');await page.locator('#comparison-prev').click();assert.equal(await page.locator('#comparison-player').getAttribute('data-prediction-phase'),'0');await page.locator('#reading-case').selectOption('glass');assert.equal(await page.locator('#comparison-player').getAttribute('data-predicting'),'false');assert.equal(await page.locator('#prediction-chapter').isVisible(),false);
 // Theme switches propagate to both retained activities and survive a reload.
 await page.locator('[data-theme-choice="dark"]').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');assert.equal(await gf.locator('html').getAttribute('data-theme'),'dark');assert.equal(await nf.locator('html').getAttribute('data-theme'),'dark');
 const themed=await page.context().newPage();await themed.goto(origin+'/spotlight-attention-lab.html#human');assert.equal(await themed.locator('html').getAttribute('data-theme'),'dark');await themed.close();await page.locator('[data-theme-choice="light"]').click();assert.equal(await gf.locator('html').getAttribute('data-theme'),'light');
 await page.locator('#tab-society').click();await page.locator('#allocation-sandbox>summary').click();assert.ok(await page.locator('#control-room').evaluate(el=>el.compareDocumentPosition(document.querySelector('.social-exercise-intro'))&Node.DOCUMENT_POSITION_FOLLOWING));await page.locator('.spectacle-plate').scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.querySelector('.spectacle-plate img').naturalWidth>1000);for(const s of ['capture','assessment','cooperation']){await page.locator(`[data-social="${s}"]`).click();await page.locator('#social-act').click();assert.ok((await page.locator('#social-feedback').textContent()).length>50);assert.equal(await page.locator('#social-details dt').count(),4);}
 // The control room is playable through controls, including budget rejection,
 // individual traces, a finite check-in, an eight-cycle win and a replay.
 assert.match(await page.locator('#social-example').textContent(),/Example response/);
 await page.locator('#room-mission').selectOption('assessment');await page.locator('#room-start').click();
 assert.equal(await page.locator('#room-groups [data-reader]').count(),120);
 for(const theme of ['dark','light']){await page.locator(`[data-theme-choice="${theme}"]`).click();const contrast=await page.locator('[data-reader="0"]').evaluate(el=>{const rgb=s=>s.match(/[\d.]+/g).slice(0,3).map(Number);const lum=a=>a.map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4;}).reduce((n,x,i)=>n+x*[.2126,.7152,.0722][i],0);const a=lum(rgb(getComputedStyle(el).color)),b=lum(rgb(getComputedStyle(el.closest('.room-group')).backgroundColor));return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);});assert.ok(contrast>=4.5,`${theme} reader signal contrast ${contrast}`);}

 assert.equal(await page.locator('#room-mission').isEnabled(),false);
 await page.locator('.room-group-settings summary').click();await page.locator('#room-units-0').selectOption('3');assert.equal(await page.locator('#room-run').isEnabled(),false);assert.match(await page.locator('#room-plan-note').textContent(),/Over budget/);await page.locator('#room-units-0').selectOption('2');
 const heldPrefix=await page.locator('#room-prefix').textContent();await page.locator('#reading-case').selectOption('cat');assert.equal(await page.locator('#room-prefix').textContent(),heldPrefix);
 for(let round=0;round<8;round++){
  await page.locator('#room-batch').selectOption([2,4].includes(round)?'quiet':'scaffold');assert.equal(await page.locator('#room-action-5').inputValue(),[2,4].includes(round)?'quiet':'scaffold');
  await page.locator('#room-run').click();assert.equal(await page.locator('#control-room').getAttribute('data-round'),String(round+1));
  if(round===0){await page.locator('[data-reader="0"]').click();assert.match(await page.locator('#room-reader').textContent(),/Reader 1/);await page.locator('[data-reader="0"]').press('ArrowRight');assert.match(await page.locator('#room-reader').textContent(),/Reader 2/);assert.equal(await page.locator('#room-groups [tabindex="0"]').count(),1);await page.locator('#room-survey').click();assert.equal(await page.locator('#room-survey').isEnabled(),false);assert.equal(await page.locator('.room-survey-groups>span').count(),6);}
 }
 assert.match(await page.locator('#room-result-title').textContent(),/Contract satisfied/);assert.equal(await page.locator('#room-run').isEnabled(),false);assert.equal(await page.locator('#room-log tr').count(),8);assert.equal(await page.locator('#room-comparison-rows tr').count(),1);
 if(process.env.ATTENTION_QA_DIR){await page.locator('#control-room').screenshot({path:path.join(process.env.ATTENTION_QA_DIR,'control-room-desktop.png')});}
 await page.locator('#room-replay').click();await page.locator('#room-mission').selectOption('cooperation');await page.locator('#room-start').click();assert.equal(await page.locator('#control-room').getAttribute('data-round'),'0');assert.equal(await page.locator('#room-comparison-rows tr').count(),1);
 await page.locator('#room-ranking').selectOption('clicks');for(let g=0;g<6;g++)await page.locator('#room-action-'+g).selectOption('discuss');await page.locator('#room-run').click();
 const current=id=>page.locator('#chapter-rail [aria-current="page"]').getAttribute('id');await page.locator('#tab-society').press('Home');assert.equal(await current(),'tab-intro');await page.locator('#tab-intro').press('ArrowLeft');assert.equal(await current(),'tab-synthesis');await page.locator('#tab-synthesis').press('ArrowRight');assert.equal(await current(),'tab-intro');await page.locator('#tab-intro').press('ArrowDown');assert.equal(await current(),'tab-paper');await page.locator('#tab-paper').press('End');assert.equal(await current(),'tab-synthesis');assert.equal(await page.locator('#synthesis .closing-inquiry').isVisible(),true);
 const chapters=['intro','paper','queries','practice','training','numbers','human','compare','social','society','synthesis'],goChapter=id=>page.evaluate(id=>window.spotlightGo(id),id);
 // Responsive checks include every retained game mode inside its host iframe.
 const overflow=()=>page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 for(const width of [320,390,768,1440]){
  await page.setViewportSize({width,height:900});await goChapter('intro');if(width===390&&process.env.ATTENTION_QA_DIR){await page.locator('#framing').screenshot({path:path.join(process.env.ATTENTION_QA_DIR,'editorial-opening-mobile.png')});}if(width<1200){assert.equal(await page.locator('#chapter-bar').isVisible(),true);await page.locator('#chapter-contents').click();assert.equal(await page.locator('#chapter-rail').isVisible(),true);await page.locator('#rail-close').click();assert.equal(await page.locator('#chapter-rail').isVisible(),false);}else assert.equal(await page.locator('#chapter-bar').isVisible(),false);for(const name of chapters){await goChapter(name);assert.equal(await overflow(),false,`outer overflow ${width} ${name}`);if(name==='compare'){if(width===390&&process.env.ATTENTION_QA_DIR)await page.locator('#comparison-player').screenshot({path:path.join(process.env.ATTENTION_QA_DIR,'reading-together-mobile.png')});const left=await page.locator('.comparison-animation-human').boundingBox(),right=await page.locator('.comparison-animation-machine').boundingBox();assert.ok(right.x>left.x);assert.equal(right.y,left.y);}if(name==='society'&&process.env.ATTENTION_QA_DIR&&width===390){await page.locator('#control-room').screenshot({path:path.join(process.env.ATTENTION_QA_DIR,'control-room-mobile.png')});}}
  await goChapter('practice');for(let level=1;level<=7;level++){await game.locator(`[data-level="${level}"]`).click();assert.equal(await gf.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`game overflow ${width} level ${level}`);}
 }
 if(process.env.ATTENTION_QA_DIR){const out=process.env.ATTENTION_QA_DIR;for(const name of chapters){await goChapter(name);if(name==='practice')await game.locator('[data-level="6"]').click();await page.screenshot({path:path.join(out,name+'-revised.png'),fullPage:true});}await page.setViewportSize({width:390,height:844});await goChapter('human');await page.screenshot({path:path.join(out,'human-mobile-revised.png'),fullPage:true});}
 if(process.env.ATTENTION_QA_DIR){await page.setViewportSize({width:1440,height:1000});await page.locator('[data-theme-choice="dark"]').click();for(const name of ['intro','paper','human','compare','social']){await goChapter(name);await page.screenshot({path:path.join(process.env.ATTENTION_QA_DIR,name+'-dark.png'),fullPage:true});}await page.locator('[data-theme-choice="light"]').click();}
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:1000});await goChapter('compare');await page.locator('#comparison-reset').click();await page.locator('#comparison-predict').click();await page.locator('#comparison-play').click();await page.locator('#comparison-next').click();await page.locator('#comparison-next').click();assert.equal(await page.locator('[data-next-token]').count(),2);const clipped=await page.locator('.prediction-computation').evaluate(el=>{const bounds=el.parentElement.getBoundingClientRect();return [...el.children].some(child=>{const r=child.getBoundingClientRect();return r.top<bounds.top||r.bottom>bounds.bottom;});});assert.equal(clipped,false,`prediction content clipped at ${width}`);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`prediction overflow at ${width}`);if(process.env.ATTENTION_QA_DIR)await page.locator('.comparison-animation-columns').screenshot({path:path.join(process.env.ATTENTION_QA_DIR,`prediction-${width}.png`)});}
 // Text and all non-WebGL activities survive unavailable 3D modules.
 const landing=await browser.newPage();await landing.goto(origin+'/spotlight-attention-lab.html#framing');await landing.locator('#intro').waitFor();assert.ok(landing.url().endsWith('#intro'));await landing.goto(origin+'/spotlight-attention-lab.html#machine');await landing.locator('#paper:not([hidden])').waitFor();assert.ok(landing.url().endsWith('#paper'));await landing.goto(origin+'/spotlight-attention-lab.html#compare');await landing.locator('#compare').waitFor();assert.equal(await landing.locator('#intro').isVisible(),false);await landing.close();
 const fallback=await browser.newPage();await fallback.route('**/brain.js',route=>route.abort());await fallback.goto(origin+'/spotlight-attention-lab.html#human');await fallback.locator('#brain-fallback').waitFor();await fallback.locator('button[data-moment="4"]').click();assert.match(await fallback.locator('#moment-title').textContent(),/Check and revise/);await fallback.close();
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.deepEqual(failed,[]);
 console.log(JSON.stringify({puzzles,numericalCases:numerical.length,sharedExamples:3,introduction:'default landing, ten chapters, entry routes, legacy links, chapter rail keyboard navigation and the mobile contents panel verified',widths:[320,390,768,1440],controlRoom:'120 readers; over-budget blocked; eight-cycle win; check-in and replay verified',comparison:'word-by-word reading through computed next-token prediction; human alternatives, vocabulary softmax, appended outputs, pause/navigation, stable columns',themes:'light/dark, retained iframes, persistence',webgl:'40960 triangles; five network renders; bright at 10% opacity; human motion, progress, pause/resume and reduced motion verified',training:'gradient verified; loss decreased; inference fixed weights',fallback:'passed',errors,externalRequests:external.length}));
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
